CUDA_VISIBLE_DEVICES=5 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_metricbased_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --transfer_l --train 0 --test_epoch 36 --test_sup_num 16 --test_write_file "./test_result/chembl/protonet"
CUDA_VISIBLE_DEVICES=4 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_ddg_attn_newsplit --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --train 0 --test_epoch 43 --test_sup_num 16 --test_write_file "./test_result/chembl/meta_delta"
CUDA_VISIBLE_DEVICES=3 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_qsar_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --transfer_l --train 0 --test_epoch 24 --test_sup_num 16 --test_write_file "./test_result/chembl/transfer_dg"
CUDA_VISIBLE_DEVICES=2 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_ddg_attn_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --transfer_l --train 0 --test_epoch 20 --test_sup_num 16 --test_write_file "./test_result/chembl/transfer_ddg"
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_qsar_newsplit --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --train 0 --test_epoch 25 --test_sup_num 16 --test_write_file "./test_result/chembl/meta_dg"

python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_metricbased_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --transfer_l --train 0 --test_epoch 49 --test_sup_num 16 --test_write_file "./test_result/bdb/protonet"
python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_ddg_attn_new --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --train 0 --test_epoch 90 --test_sup_num 16 --test_write_file "./test_result/bdb/meta_delta"
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_qsar_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --transfer_l --train 0 --test_epoch 49 --test_sup_num 16 --test_write_file "./test_result/bdb/transfer_dg"
python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_ddg_attn_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --transfer_l --train 0 --test_epoch 24 --test_sup_num 16 --test_write_file "./test_result/bdb/transfer_ddg"
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_qsar --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --train 0 --test_epoch 49 --test_sup_num 16 --test_write_file "./test_result/bdb/meta_dg"

python main_reg.py --datasource=fsmol --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_fsmol_metricbased_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --transfer_l --train 0 --test_epoch 49 --test_sup_num 16 --test_write_file "./test_result/fsmol/protonet"
python main_reg.py --datasource=fsmol --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_fsmol_reg_newddg --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --train 0 --test_epoch 43 --test_sup_num 16 --test_write_file "./test_result/fsmol/meta_delta"
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=fsmol --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_fsmol_reg_qsar_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --transfer_l --train 0 --test_epoch 49 --test_sup_num 16 --test_write_file "./test_result/fsmol/transfer_dg"
python main_reg.py --datasource=fsmol --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_fsmol_reg_ddg_attn_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --transfer_l --train 0 --test_epoch 45 --test_sup_num 16 --test_write_file "./test_result/fsmol/transfer_ddg"
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=fsmol --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_fsmol_reg_qsar --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --train 0 --test_epoch 49 --test_sup_num 16 --test_write_file "./test_result/fsmol/meta_dg"

## expert test fep
# meta_delta
CUDA_VISIBLE_DEVICES=5 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_ddg_attn_newsplit --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --train 0 --test_epoch 43 --test_sup_num 8 --test_write_file "./test_result_fep/chembl/meta_delta" --expert_test fep
# meta_delta BDB
python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_ddg_attn_new --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --train 0 --test_epoch 90 --test_sup_num 8 --test_write_file "./test_result_fep/bdb/meta_delta" --expert_test fep
# transfer_ddg
CUDA_VISIBLE_DEVICES=4 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_ddg_attn_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --transfer_l --train 0 --test_epoch 20 --test_sup_num 8 --test_write_file "./test_result_fep/chembl/transfer_ddg" --expert_test fep
# protonet
CUDA_VISIBLE_DEVICES=3 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_metricbased_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --transfer_l --train 0 --test_epoch 36 --test_sup_num 8 --test_write_file "./test_result_fep/chembl/protonet" --expert_test fep
# transfer_dg
CUDA_VISIBLE_DEVICES=2 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_qsar_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --transfer_l --train 0 --test_epoch 24 --test_sup_num 8 --test_write_file "./test_result_fep/chembl/transfer_dg" --expert_test fep
# meta_dg
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_qsar_newsplit --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --train 0 --test_epoch 25 --test_sup_num 8 --test_write_file "./test_result_fep/chembl/meta_dg" --expert_test fep

## expert test davis
# protonet
python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_metricbased_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --transfer_l --train 0 --test_epoch 49 --test_sup_num 8 --test_write_file "./test_result_davis/bdb/protonet" --expert_test davis
# meta_delta
python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_ddg_attn_new --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --train 0 --test_epoch 90 --test_sup_num 8 --test_write_file "./test_result_davis/bdb/meta_delta" --expert_test davis
# transfer_dg
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_qsar_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --transfer_l --train 0 --test_epoch 49 --test_sup_num 8 --test_write_file "./test_result_davis/bdb/transfer_dg" --expert_test davis
# transfer_ddg
python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_ddg_attn_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --transfer_l --train 0 --test_epoch 24 --test_sup_num 8 --test_write_file "./test_result_davis/bdb/transfer_ddg" --expert_test davis
# meta_dg
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=bdb --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_bdb_reg_qsar --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --train 0 --test_epoch 49 --test_sup_num 8 --test_write_file "./test_result_davis/bdb/meta_dg" --expert_test davis

CUDA_VISIBLE_DEVICES=5 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_metricbased_newsplit_transfer  --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --transfer_l           --train 0 --test_epoch 36 --test_sup_num 16 --test_write_file "./test_result_c2b/chembl/protonet" &
CUDA_VISIBLE_DEVICES=4 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_ddg_attn_newsplit          --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg              --train 0 --test_epoch 43 --test_sup_num 16 --test_write_file "./test_result_c2b/chembl/Meta-DDG" &
CUDA_VISIBLE_DEVICES=3 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_qsar_newsplit_transfer     --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar --transfer_l    --train 0 --test_epoch 24 --test_sup_num 16 --test_write_file "./test_result_c2b/chembl/Transfer-DG" &
CUDA_VISIBLE_DEVICES=2 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_ddg_attn_newsplit_transfer --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --new_ddg --transfer_l --train 0 --test_epoch 20 --test_sup_num 16 --test_write_file "./test_result_c2b/chembl/Transfer-DDG" &
CUDA_VISIBLE_DEVICES=1 python main_reg.py --datasource=drug --metatrain_iterations=50 --update_lr=0.001 --meta_lr=0.00015 --min_learning_rate 0.0001 --num_updates=5 --test_num_updates=5 --trial=1 --meta_batch_size=16 --drug_group=1 --logdir ./checkpoints/checkpoint_chembl_reg_qsar_newsplit              --hid_dim 2048 --sim_thres 0.2 --dim_w 2048 --qsar                 --train 0 --test_epoch 25 --test_sup_num 16 --test_write_file "./test_result_c2b/chembl/Meta-DG"
